[package]
name = "cogshell"
version = "0.1.0"
edition = "2024"
description = "CogShell: Generate parts of files with shell scripts"
authors = ["Tim Vergenz <vergenzt@gmail.com>"]
license = "MIT"
readme = "README.md"

[dependencies]
annotate-snippets = "0.12.13"
anstream = { version = "1.0.0", features = ["auto"] }
anyhow = "1"
clap = { version = "4.5.60", features = ["derive"] }
md5 = "0.8.0"
regex = "1"
strum = { version = "0.28.0", features = ["derive"] }
tempfile = "3"
thiserror = "2.0.18"
tree-sitter-bash = "0.25.1"

[dev-dependencies]
yare = "3.0.0"
