[package]
name = "cogshell"
version = "0.1.0"
edition = "2024"
description = "CogShell: Generate parts of files with shell scripts"
authors = ["Tim Vergenz <vergenzt@gmail.com>"]
license = "MIT"
readme = "README.md"

[dependencies]
annotate-snippets = { version = "0.12.16", default-features = false }
atomic_writer = { version = "0.1.0", path = "utils/atomic_writer" }
base64_encode = { version = "0.1.0", path = "utils/base64_encode" }
bpaf = { version = "0.9.24", default-features = false, features = ["derive"] }
common_prefix = { version = "0.1.0", path = "utils/common_prefix" }
fastrand = "2.4.1"
hex = { version = "0.4.3", default-features = false }
md5 = { version = "0.8.0", default-features = false }
regex = { version = "1.12.3", default-features = false }
tempfile = { version = "3.26.0", default-features = false }
