[tool.poetry]
name = "cogshell"
version = "0.1.0"
description = "CogShell: Generate parts of files with shell scripts"
authors = ["Tim Vergenz <vergenzt@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
