import re
from dataclasses import dataclass, field
from enum import StrEnum, auto
from functools import cached_property

from .errors import CogShellError

DEFAULT_ENVVAR_PREFIX: str = "COGSH_"

LINE_SEPS = [b"\r\n", b"\n"]


@dataclass
class CogShellEnviron:
    "Environment variables that may be set for duration of embedded program execution"

    FILE: str = ""
    "Absolute path to the file containing current embedded CogShell program"

    PROGRAM: str = ""
    "Path to tempfile containing the shell code being run"

    OUTPUT_PREV: str = ""
    "Path to tempfile containing the previous output of current CogShell block"

    OUTPUT_NEXT: str = ""
    "Path to tempfile to which the *next* output of current CogShell block should be written (if not using stdout)"

    EXEC_DIR: str = ""
    "Path to the temp directory containing files related to this execution"


class MarkerType(StrEnum):
    "Marker types which CogShell will process"

    PROG_START = auto()
    "Indicates start of an embedded CogShell program"

    PROG_END = auto()
    "Indicates end of an embedded CogShell program"

    OUTPUT_END = auto()
    "Indicates end of output generated by an embedded CogShell program"


MARKER_DEFAULTS: dict[MarkerType, bytes] = {
    MarkerType.PROG_START: b"[[[cogsh",
    MarkerType.PROG_END: b"]]]",
    MarkerType.OUTPUT_END: b"[[[end]]]",
}


@dataclass
class Config:
    default_shell: str = "bash"
    "The default shell to pass programs to when not specified inline"

    isolate_embeddings: bool = False
    "Whether to start new shell instances for each embedded program within a file"

    output_checksum: bool = True
    "Whether to protect output lines in CogShell'd files from accidental modification by including a hash after the `output_end` marker"

    output_line_suffix: bytes = b""
    "Optional suffix to append to each output line"

    prev_output_on_stdin: bool = True
    "Whether to send previous output to the program's stdin"

    next_output_on_stdout: bool = True
    "Whether to expect next output on the program's stdout"

    prologue: list[bytes] = field(default_factory=list)
    "Shell lines which will be prepended to each embedded program before running"

    markers: dict[MarkerType, bytes] = field(default_factory=MARKER_DEFAULTS.copy)
    "Overrides for CogShell program and output marker strings"

    envvar_prefix: str = DEFAULT_ENVVAR_PREFIX
    "Prefix for CogShell environment variable names"

    envvar_names: CogShellEnviron = field(default_factory=CogShellEnviron)
    "Overrides for names of CogShell environment variables, appended to `envvar_prefix`"

    @cached_property
    def markers_re(self) -> re.Pattern[bytes]:
        "Regex to match any marker"
        markers = (re.escape(self.markers[type]) for type in MarkerType)
        return re.compile(b"(" + b"|".join(markers) + b")" + rb"(\s+|$)", re.MULTILINE)

    @cached_property
    def marker_types_by_marker(self) -> dict[bytes, MarkerType]:
        "Mapping from marker strings to marker type"
        if len(set(self.markers.values())) != len(self.markers):
            raise CogShellError("Markers must be unique!")
        return {marker: type for type, marker in self.markers.items()}


def load_config() -> Config:
    # TODO: load from config file(s) (pyproject.toml section / special .cogshell.toml file(s)?)
    return Config()
