import os
import re
import stat
import subprocess as sp
import sys
from base64 import b64encode
from collections.abc import Iterator
from contextlib import ExitStack, contextmanager
from dataclasses import asdict, dataclass, field
from enum import StrEnum, auto
from functools import cache, cached_property
from hashlib import md5, sha1
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Optional, Self


class CogShellError(Exception):
    "Any exception raised by CogShell"

    def __init__(self, msg: str, file: str = "", line: int = 0):
        if file:
            super().__init__(f"{file}({line}): {msg}")
        else:
            super().__init__(msg)


DEFAULT_ENVVAR_PREFIX: str = "COGSH_"

CHECKSUM_FN = md5

LINE_SEPS = [b"\r\n", b"\n"]


@dataclass
class CogShellEnviron:
    "Environment variables that may be set for duration of embedded program execution."

    FILE: str = ""
    "Absolute path to the file containing current embedded CogShell program."

    PROGRAM: str = ""
    "Path to tempfile containing the shell code being run."

    OUTPUT_PREV: str = ""
    "Path to tempfile containing the previous output of current CogShell block."

    OUTPUT_NEXT: str = ""
    "Path to tempfile to which the *next* output of current CogShell block should be written (if not using stdout)."

    EXEC_DIR: str = ""
    "Path to the temp directory containing files related to this execution."


class MarkerType(StrEnum):
    "Marker types which CogShell will process"

    PROG_START = auto()
    "Indicates start of an embedded CogShell program"

    PROG_END = auto()
    "Indicates end of an embedded CogShell program"

    OUTPUT_END = auto()
    "Indicates end of output generated by an embedded CogShell program"


MARKER_DEFAULTS: dict[MarkerType, bytes] = {
    MarkerType.PROG_START: b"[[[cogsh",
    MarkerType.PROG_END: b"]]]",
    MarkerType.OUTPUT_END: b"[[[end]]]",
}


@dataclass
class Config:
    output_checksum: bool = True
    "Whether to protect output lines in CogShell'd files from accidental modification by including a hash after the `output_end` marker."

    output_line_suffix: bytes = b""
    "Optional suffix to append to each output line."

    prev_output_on_stdin: bool = True
    "Whether to send previous output to the program's stdin."

    next_output_on_stdout: bool = True
    "Whether to expect next output on the program's stdout."

    prologue: list[bytes] = field(default_factory=list)
    "Shell lines which will be prepended to each embedded program before running."

    markers: dict[MarkerType, bytes] = field(default_factory=MARKER_DEFAULTS.copy)
    "Overrides for CogShell program and output marker strings."

    envvar_prefix: str = DEFAULT_ENVVAR_PREFIX
    "Prefix for CogShell environment variable names."

    envvar_names: CogShellEnviron = field(default_factory=CogShellEnviron)
    "Overrides for names of CogShell environment variables, appended to `envvar_prefix`."

    @cached_property
    def markers_re(self) -> re.Pattern[bytes]:
        "Regex to match any marker"
        markers = (re.escape(self.markers[type]) for type in MarkerType)
        return re.compile(b"(" + b"|".join(markers) + b")" + rb"(\s+|$)", re.MULTILINE)

    @cached_property
    def marker_types_by_marker(self) -> dict[bytes, MarkerType]:
        "Mapping from marker strings to marker type"
        if len(set(self.markers.values())) != len(self.markers):
            raise CogShellError("Markers must be unique!")
        return {marker: type for type, marker in self.markers.items()}


@cache
def line_for(file_content: bytes, loc: int) -> int:
    return file_content.count(b"\n", 0, loc)


@dataclass
class EmbeddedProgram:
    config: Config
    file: Path
    file_content: bytes

    prog_start_marker: re.Match[bytes]
    prog_end_marker: re.Match[bytes]
    output_end_marker: re.Match[bytes]

    @cached_property
    def _program_raw(self) -> bytes:
        "Raw bytes of program between start marker and end marker"
        return self.file_content[
            self.prog_start_marker.end() + 1 : self.prog_end_marker.start()
        ]

    @cached_property
    def _prog_start_line_start(self) -> int:
        "Location of the start of the line containing the prog_start_marker"
        return max(self.file_content.rfind(b"\n", 0, self.prog_start_marker.start()), 0)

    @cached_property
    def _program_lines(self) -> list[bytes]:
        "Lines between prog_start_marker and prog_end_marker"
        return self.file_content[
            self._prog_start_line_start : self.prog_end_marker.start()
        ].splitlines()

    @cached_property
    def _program_lines_common_pfx(self) -> bytes:
        "Common prefix of lines between prog_start_marker and prog_end_marker"
        non_blank_lines = [line for line in self._program_lines if line.strip()]
        return os.path.commonprefix(non_blank_lines)  # type: ignore

    @cached_property
    def program(self) -> bytes:
        """
        Program bytes after stripping common prefix from program lines.

        See:
        - https://github.com/vergenzt/cog/blob/1ef2543fe49f4b322736f37bb9959579e440d56d/cogapp/cogapp.py#L477-L479
        - https://github.com/vergenzt/cog/blob/1ef2543fe49f4b322736f37bb9959579e440d56d/cogapp/cogapp.py#L128-L131
        """
        if b"\n" in self._program_raw:
            return re.sub(
                b"^" + re.escape(self._program_lines_common_pfx),
                b"",
                self._program_raw,
                re.MULTILINE,
            )
        else:
            return self._program_raw

    @cached_property
    def _output_prev_raw(self) -> bytes:
        """
        Raw bytes between prog_end_marker and output_end_marker
        """
        return self.file_content[
            self.prog_end_marker.end() + 1 : self.output_end_marker.start()
        ]

    @cached_property
    def _output_end_line_end(self) -> int:
        """
        Location of the end of the line containing output_end_marker (or -1 if no newline after marker).
        """
        return self.file_content.find(b"\n", self.output_end_marker.end())

    @cached_property
    def _output_prev_hash_match(self) -> re.Match[bytes]:
        "Returns a match which contains a `hash` group containing checksum hash if present, None otherwise."
        hash_match = re.match(
            rb"( *\(checksum: (?P<hash>[a-f0-9]+)\))?",
            self.file_content[self.output_end_marker.end() : self._output_end_line_end],
        )
        assert hash_match, "Regex should always match (may be empty though)"
        return hash_match

    @property
    def _output_prev_hash_matched(self) -> Optional[bytes]:
        "Returns matched checksum hex digest if present in file, None otherwise."
        return self._output_prev_hash_match.group("hash")

    @cached_property
    def _output_prev_hash(self) -> bytes:
        hasher = CHECKSUM_FN()
        hasher.update(self._output_prev_raw)
        return hasher.hexdigest().encode()

    @cached_property
    def _output_whitespace_pfx(self) -> bytes:
        """
        Whitespace to prepend to non-blank output lines.

        To be compatible with `cogapp`, we only prefix output with leading common
        whitespace in the *first* and *last* program lines.
        https://github.com/vergenzt/cog/blob/1ef2543fe49f4b322736f37bb9959579e440d56d/cogapp/cogapp.py#L137
        """
        first_and_last_lines = [
            line
            for i, line in enumerate(self._program_lines)
            if i in (0, len(self._program_lines) - 1)
        ]
        leading_whitespaces = [
            line[: -len(line.lstrip())] for line in first_and_last_lines if line.strip()
        ]
        return os.path.commonprefix(leading_whitespaces)  # type: ignore

    @cached_property
    def output_prev(self) -> bytes:
        """
        Previous output bytes after stripping CogShell-injected whitespace.
        """
        return re.sub(
            b"^" + re.escape(self._output_whitespace_pfx),
            b"",
            self._output_prev_raw,
            re.MULTILINE,
        )

    @classmethod
    def from_file(cls, config: Config, file: Path) -> Iterator[Self]:
        """
        Find and yield program instances from then given file with the given config.
        """

        markers = config.markers
        marker_types = config.marker_types_by_marker
        content = file.read_bytes()

        matches_iter = re.finditer(config.markers_re, content)

        while True:
            matches: list[re.Match[bytes]] = []

            # try to match each of the markers
            for next_marker_type in MarkerType:
                next_marker = markers[next_marker_type]
                next_match = next(matches_iter, None)
                if not next_match:
                    # no marker found and we're just starting out
                    if not matches:
                        # then stop trying to look for markers
                        break
                    # no marker found and we previously started a marker series
                    else:
                        prev_marker = matches[-1].group()
                        prev_marker_type = marker_types[prev_marker]
                        raise CogShellError(
                            f"Missing {next_marker_type.name} marker `{next_marker!r}` following {prev_marker_type} marker `{prev_marker!r}`",
                            file=str(file),
                            line=line_for(content, matches[-1].start()),
                        )
                # marker found, but not the right one
                elif (marker := next_match.group()) != marker:
                    marker_type = marker_types[marker]
                    raise CogShellError(
                        f"Unexpected {marker_type} marker `{marker!r}`, expected {next_marker_type} marker `{next_marker!r}`",
                        file=str(file),
                        line=line_for(content, next_match.start()),
                    )
                # correct marker found
                else:
                    matches.append(next_match)

            yield cls(config, file, content, *matches)

    @cached_property
    def execution_dir_name(self) -> str:
        return "-".join(
            [
                "cogshell",
                self.file.name,
                b64encode(
                    sha1(self.file_content, usedforsecurity=False).digest()
                ).decode(),
                str(self.prog_end_marker.start()),
            ]
        )

    @contextmanager
    def execution_dir(self) -> Iterator[Path]:
        with TemporaryDirectory(prefix=self.execution_dir_name + "-") as tmpdir:
            yield Path(tmpdir)

    def execution_env(self, exec_dir: Path) -> CogShellEnviron:
        env = CogShellEnviron(
            EXEC_DIR=str(exec_dir),
            FILE=str(self.file.absolute()),
            PROGRAM=str(program_file := exec_dir / "program"),
            OUTPUT_PREV=str(output_prev := exec_dir / "output_prev"),
            OUTPUT_NEXT=str(output_next := exec_dir / "output_next"),
        )
        program_file.write_bytes(self.program)
        program_file.chmod(stat.S_IEXEC | stat.S_IREAD)
        output_prev.write_bytes(self.output_prev)
        output_next.touch()
        return env

    def execute(self):
        "Execute the found program."

        with ExitStack() as stack:
            exec_dir = stack.enter_context(self.execution_dir())

            output_checksum = self.config.output_checksum
            if self.config.output_checksum:
                if not (hash_match := self._output_prev_hash_match):
                    print(
                        f"Warning: {self.file}({line_for(self.output_end_marker.end())}): {output_checksum=} but no output checksum detected",
                        file=sys.stderr,
                    )
                elif hash_match.group("hash") != self._output_prev_hash:
                    raise CogShellError(
                        "Output checksum does not match!",
                        file=str(self.file),
                        line=line_for(hash_match.start("hash")),
                    )
                else:
                    pass

            exec_env = self.execution_env(exec_dir)
            exec_env_dict = {
                (
                    self.config.envvar_prefix
                    + asdict(self.config.envvar_names).get(fieldname, fieldname.upper())
                ): val
                for fieldname, val in asdict(exec_env).items()
            }

            sp.run(
                self.program,
                shell=True,
                check=True,
                env=exec_env_dict,
                cwd=exec_dir,
                stdin=(
                    stack.enter_context(open(exec_env.OUTPUT_PREV, "rb"))
                    if self.config.prev_output_on_stdin
                    else sp.DEVNULL
                ),
                stdout=(
                    stack.enter_context(open(exec_env.OUTPUT_NEXT, "wb"))
                    if self.config.next_output_on_stdout
                    else None
                ),
            )

            with open(self.file, "wb") as f:
                f.write(self.file_content[: self.prog_end_marker.end()])

                for line_sep in LINE_SEPS:
                    if self._output_prev_raw.startswith(line_sep):
                        f.write(b"\n")
                        break

                hasher = CHECKSUM_FN()

                last_output_line: bytes = b""
                with open(exec_env.OUTPUT_NEXT, "rb") as output:
                    while output_line_raw_with_sep := output.readline():
                        line_sep = next(
                            filter(output_line_raw_with_sep.endswith, LINE_SEPS), b""
                        )
                        output_line_raw = output_line_raw_with_sep[: -len(line_sep)]
                        output_line = b"".join(
                            [
                                self._output_whitespace_pfx,
                                output_line_raw,
                                self.config.output_line_suffix,
                                line_sep,
                            ]
                        )
                        f.write(output_line)
                        hasher.update(output_line)
                        last_output_line = output_line

                for line_sep in LINE_SEPS:
                    if self._output_prev_raw.endswith(
                        line_sep
                    ) and not last_output_line.endswith(line_sep):
                        f.write(line_sep)
                        f.write(self._output_whitespace_pfx)

                f.write(self.config.markers[MarkerType.OUTPUT_END])
                if output_checksum:
                    f.write(b" (")
                    f.write(hasher.hexdigest().encode())
                    f.write(b")")

                f.write(self.file_content[self._output_prev_hash_match.end() + 1 :])
